Create Homework1
Anal0h/java pull request #1
Opened 2023-09-11 09:07 UTC by Anal0h

2023-09-11 13:52 UTC, KozlovAV426 requested changes

2023-09-11 13:52 UTC, KozlovAV426 commented on Homework1
> +public class Homework1 {
в название файла добавить расширение .java

2023-09-11 13:52 UTC, KozlovAV426 commented on Homework1
> +        int maximum1 = Math.max(x, y);
лучше не добавлять числа в названия переменных, тогда уж firstMaximum & secondMaximum

2023-09-11 13:52 UTC, KozlovAV426 commented on Homework1
> +            res = res*i;
добавить пробелы между операторами -> res = res * i

2023-09-11 13:52 UTC, KozlovAV426 commented on Homework1
> +                if (i*j < 10){
пробелы добавить

2023-09-11 13:52 UTC, KozlovAV426 commented on Homework1
> +        return sum/l;
пробелы

2023-09-11 13:52 UTC, KozlovAV426 commented on Homework1
> +        return arr1;
лучше было бы не arr1, а reversedArray + добавить пробелы

2023-09-11 13:52 UTC, KozlovAV426 commented on Homework1
> +                    arr[j+1] = t;
пробелы

2023-09-11 13:52 UTC, KozlovAV426 commented on Homework1
> +                System.arraycopy(arr, i + 1, a, i, l-i-1);
пробелы

2023-09-12 23:31 UTC, ASemenovng requested changes

2023-09-12 23:31 UTC, ASemenovng commented on Homework1.java
> +        int FirstMax = Math.max(x, y);
Переменные принято называть с маленькой буквы, то есть firstMax, а не FirstMax. Аналогично и остальные

2023-09-12 23:36 UTC, ASemenovng commented on Homework1.java
> +        int[] ReverseArr = new int[l];
Аналогично ReverseArr -> reverseArr 
И тут можно было обойтись без доп массива

2023-09-17 22:48 UTC, ASemenovng requested changes

2023-09-17 22:48 UTC, ASemenovng commented on Homework1.java
> +    static double average(int... nums) {
А в чем отличие?) Ты бы итак получила NaN, если бы в предыдущей версии вызвала average()

2023-09-18 10:48 UTC, ASemenovng requested changes

2023-09-18 10:48 UTC, ASemenovng commented on Homework1.java
> +    static int average(int... nums) {
Почему return int?

2023-09-27 18:46 UTC, ASemenovng requested changes

2023-09-27 18:46 UTC, ASemenovng commented on Homework1.java
> +    static int max(int x, int y, int z) {
Можно просто max(max(...),...), чтобы не создавать лишних переменных

2023-09-27 18:46 UTC, ASemenovng commented on Homework1.java
> +        if (n == BigInteger.ZERO || n == BigInteger.ONE) {
Ссылочные типы данных нужно сравнивать на equals(), а не ==

2023-09-27 18:46 UTC, ASemenovng commented on Homework1.java
> +    static int[] reverse(int[] arr) {
Можно ли сделать без доп памяти?

2023-09-30 12:12 UTC, KozlovAV426 reviewed
ok

2023-09-30 12:13 UTC, merged